/**
 * Legacy parity tests.
 *
 * Verifies that the JavaScript calculation methods produce the same results
 * as the original Python implementation. Fixtures are generated by running:
 *
 *   legacy/.venv/bin/python legacy/generate_fixtures.py
 *
 * Tests cover:
 * - Shared sub-calculations (calculateSingleEffect, calculateProject, etc.)
 * - Three voting methods: credenceWeighted, myFavoriteTheory, mec
 *
 * Known differences:
 * - Tie-breaking: Python uses insertion-order max(), JS uses alphabetical sort.
 *   This can cause divergence when project scores are exactly equal.
 * - MEC algorithm: The original Python MEC averages parameters before evaluation
 *   and splits on risk_profile. The JS MEC (and these fixtures) use expected-value
 *   across all worldviews. See docs/legacy-calculation-differences.md.
 */

import { describe, it, expect } from 'vitest';
import {
  calculateSingleEffect,
  calculateProject,
  calculateAllProjects,
  adjustForExtinctionRisk,
  getDiminishingReturnsFactor,
} from '../src/utils/projectScoring.js';
import { computeMarcusAllocation } from '../src/utils/marcusCalculation.js';

import subcalcFixtures from './fixtures/legacy_subcalculations.json';
import votingFixtures from './fixtures/legacy_voting_methods.json';

// Tolerance for floating-point comparison.
// Sub-calculations should match to high precision (same algorithm, same data).
// End-to-end allocations can accumulate small FP differences over many iterations.
const SUBCALC_TOLERANCE = 1e-6;
const ALLOCATION_TOLERANCE = 1e-6; // $M — funding values are multiples of 10

// =============================================================================
// SUB-CALCULATION TESTS
// =============================================================================

describe('Legacy parity: sub-calculations', () => {
  const projectData = subcalcFixtures.project_data;

  const singleEffectTests = subcalcFixtures.tests.filter(
    (t) => t.function === 'calculateSingleEffect'
  );
  const projectTests = subcalcFixtures.tests.filter((t) => t.function === 'calculateProject');
  const allProjectsTests = subcalcFixtures.tests.filter(
    (t) => t.function === 'calculateAllProjects'
  );
  const extinctionTests = subcalcFixtures.tests.filter(
    (t) => t.function === 'adjustForExtinctionRisk'
  );
  const drTests = subcalcFixtures.tests.filter((t) => t.function === 'getDiminishingReturnsFactor');

  describe('calculateSingleEffect', () => {
    for (const test of singleEffectTests) {
      it(test.description, () => {
        const { effect_data, moral_weight, discount_factors, risk_profile } = test.inputs;
        const result = calculateSingleEffect(
          effect_data,
          moral_weight,
          discount_factors,
          risk_profile
        );
        expect(result).toBeCloseTo(test.expected, 6);
      });
    }
  });

  describe('calculateProject', () => {
    for (const test of projectTests) {
      it(test.description, () => {
        const { project_data, moral_weights, discount_factors, risk_profile } = test.inputs;
        const result = calculateProject(
          project_data,
          moral_weights,
          discount_factors,
          risk_profile
        );
        expect(result).toBeCloseTo(test.expected, 6);
      });
    }
  });

  describe('calculateAllProjects', () => {
    for (const test of allProjectsTests) {
      it(test.description, () => {
        const { moral_weights, discount_factors, risk_profile } = test.inputs;
        const result = calculateAllProjects(
          projectData,
          moral_weights,
          discount_factors,
          risk_profile
        );
        for (const [projectId, expectedValue] of Object.entries(test.expected)) {
          expect(result[projectId]).toBeCloseTo(expectedValue, 6);
        }
      });
    }
  });

  describe('adjustForExtinctionRisk', () => {
    for (const test of extinctionTests) {
      it(test.description, () => {
        const { project_values, p_extinction } = test.inputs;
        const result = adjustForExtinctionRisk(project_values, projectData, p_extinction);
        for (const [projectId, expectedValue] of Object.entries(test.expected)) {
          expect(result[projectId]).toBeCloseTo(expectedValue, 6);
        }
      });
    }
  });

  describe('getDiminishingReturnsFactor', () => {
    for (const test of drTests) {
      it(test.description, () => {
        const { project_id, current_funding } = test.inputs;
        const result = getDiminishingReturnsFactor(projectData, project_id, current_funding);
        expect(result).toBeCloseTo(test.expected, 6);
      });
    }
  });
});

// =============================================================================
// VOTING METHOD TESTS
// =============================================================================

describe('Legacy parity: voting methods', () => {
  const projectData = votingFixtures.project_data;

  for (const method of [
    'credenceWeighted',
    'myFavoriteTheory',
    'mec',
    'borda',
    'splitCycle',
    'lexicographicMaximin',
    'nashBargaining',
    'met',
    'msa',
  ]) {
    const methodTests = votingFixtures.tests.filter((t) => t.method === method);

    describe(method, () => {
      for (const test of methodTests) {
        it(test.description, () => {
          const { worldviews, budget, increment_size } = test.inputs;

          const { allocations, funding } = computeMarcusAllocation(
            projectData,
            worldviews,
            method,
            budget,
            increment_size
          );

          // Compare funding ($M values)
          for (const [projectId, expectedFunding] of Object.entries(test.expected_funding)) {
            expect(funding[projectId]).toBeCloseTo(expectedFunding, ALLOCATION_TOLERANCE);
          }

          // Compare allocation percentages
          for (const [projectId, expectedPct] of Object.entries(test.expected_allocations_pct)) {
            expect(allocations[projectId]).toBeCloseTo(expectedPct, ALLOCATION_TOLERANCE);
          }
        });
      }
    });
  }
});
