AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Quiz Demo Share URL API

Parameters:
  TursoDatabaseUrl:
    Type: String
    Description: Turso database URL
    NoEcho: true
  TursoAuthToken:
    Type: String
    Description: Turso auth token
    NoEcho: true

Resources:
  ShareFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: quiz-demo-share
      CodeUri: share/
      Handler: index.handler
      Runtime: nodejs20.x
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          TURSO_DATABASE_URL: !Ref TursoDatabaseUrl
          TURSO_AUTH_TOKEN: !Ref TursoAuthToken

  ShareFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !GetAtt ShareFunction.Arn
      Cors:
        AllowOrigins:
          - '*'
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowHeaders:
          - Content-Type

  # Permission for Function URL public access
  ShareFunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ShareFunction
      Action: lambda:InvokeFunctionUrl
      Principal: '*'
      FunctionUrlAuthType: NONE

  # Additional permission required for public Function URLs
  ShareFunctionInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ShareFunction
      Action: lambda:InvokeFunction
      Principal: '*'

Outputs:
  ShareFunctionUrl:
    Description: Function URL for the Share API
    Value: !GetAtt ShareFunctionUrl.FunctionUrl
  ShareFunctionArn:
    Description: ARN of the Share function
    Value: !GetAtt ShareFunction.Arn
